回報表單題目編號修正
SiongSng/cap-countdown pull request #13
Opened 2023-05-01 15:11 UTC by jackychiu0207

將題目編號修正成真正的題號

2023-05-02 10:33 UTC, SiongSng requested changes

2023-05-02 10:33 UTC, SiongSng commented on lib/src/exam/optional_question.dart
> +  @JsonKey(name: 'number')
好奇這裡為什麼要改？

2023-05-02 11:55 UTC, SiongSng requested changes

2023-05-02 11:55 UTC, SiongSng commented on lib/src/widgets/choice_button.dart
> +class _DisableOptionButton {}
這個是要做什麼的？

2023-05-02 11:55 UTC, SiongSng commented on lib/src/exam/subject_question.dart
> +    String getQuestionNumber(){
建議可以把這種重複的函式移動到另一個 class，不然會有太多重複的函式，這裡就有出現過類似的函式了：
https://github.com/SiongSng/cap-countdown/blob/b664a0f8f53ef6c687274c772b053967c9b8501b/lib/src/pages/exam/simulation_exam_page.dart#L456

2023-05-03 12:47 UTC, SiongSng requested changes

2023-05-03 12:47 UTC, SiongSng commented on lib/src/exam/question_meta.dart
> +    if (question is SingleChoiceQuestion) {
建議保留原來的 const 不要儲存 question 這個物件，另外立一個 factory 來處理從 question 到 questionNumber

2023-05-03 14:03 UTC, jackychiu0207 commented on lib/src/exam/question_meta.dart
> +    if (question is SingleChoiceQuestion) {
已完成更改

2023-05-04 13:08 UTC, SiongSng requested changes
最後一點小問題

2023-05-04 13:08 UTC, SiongSng commented on lib/src/pages/exam/paper_simulation_exam_page.dart
> +                const SizedBox(height: 12),
圖片換位置放反而更怪，如要修正文字溢出的問題，請另行開設 PR

![圖片](https://user-images.githubusercontent.com/48402225/236213714-98d77810-99a3-486e-99ab-55fd2705a50d.png)

2023-05-04 13:44 UTC, SiongSng approved these changes
LGTM

2023-05-04 13:59 UTC, merged