Feature/cross out choice
SiongSng/cap-countdown pull request #44
Opened 2023-05-22 09:42 UTC by jackychiu0207

2023-05-25 10:06 UTC, SiongSng requested changes
實際效果不錯，但還有一些小建議

2023-05-25 10:06 UTC, SiongSng commented on lib/src/widgets/choice_button.dart
>          }
```suggestion
        final offset = dragEndDetails.velocity.pixelsPerSecond.dx;

        if (offset != 0) {
          onEvent?.call(EventsEnum.crossOutChoice);
        }
```

有沒有考慮改成這樣？ 左右滑動都有效果，我覺得這樣子比較好用。

2023-05-25 10:06 UTC, SiongSng commented on lib/src/widgets/choice_button.dart
> +              content: Text('無法選擇已劃掉的選項！'),
```suggestion
              content: Text('無法選擇已劃掉的選項，對選項左右滑動即可取消。'),
```

或許可告知使用者如何取消排除選項的效果。
然後非手機布局（layout）的話就要改成其他提示訊息。

2023-05-25 10:31 UTC, jackychiu0207 commented on lib/src/widgets/choice_button.dart
> +      excludeFromSemantics: true,
否則此手勢會被PageView覆蓋

2023-05-25 10:31 UTC, jackychiu0207 commented on lib/src/widgets/choice_button.dart
>          }
感覺可以

2023-05-25 10:31 UTC, jackychiu0207 commented on lib/src/widgets/choice_button.dart
> +              content: Text('無法選擇已劃掉的選項！'),
OK

2023-05-25 10:31 UTC, jackychiu0207 commented on lib/src/pages/main_page.dart
> -      children: breakpoint.isPhone
不小心混到其他分支了

2023-05-25 10:31 UTC, jackychiu0207 commented on lib/src/util/events_enum.dart
> +enum EventsEnum {
已更改

2023-05-25 10:31 UTC, jackychiu0207 commented on lib/src/widgets/optional_question_view.dart
> +          onEvent: (value) {
已更改

2023-05-25 10:31 UTC, jackychiu0207 commented on lib/src/widgets/optional_question_view.dart
> +                    }
已更改

2023-05-26 09:25 UTC, SiongSng requested changes
剩下一些命名問題

2023-05-26 09:25 UTC, SiongSng commented on lib/src/widgets/choice_button.dart
> +enum ChoiceEventsEnum {
我覺得改成 `ChoiceButtonEvent` 這個名稱會更符合命名規範

2023-05-26 09:25 UTC, SiongSng commented on lib/src/widgets/optional_question_view.dart
> +    crossItemFunc(int index, QuestionChoice choice) {
```suggestion
    void crossOut(int index, QuestionChoice choice) {
```

請明確標示回傳型別與函式名稱

2023-05-26 09:25 UTC, SiongSng commented on lib/src/widgets/optional_question_view.dart
> +                  crossItemFunc(index, choice);
```suggestion
                  crossOut(index, choice);
```

2023-05-26 09:25 UTC, SiongSng commented on lib/src/widgets/optional_question_view.dart
> +              crossItemFunc(index, choice);
```suggestion
              crossOut(index, choice);
```

2023-05-26 09:29 UTC, jackychiu0207 commented on lib/src/widgets/choice_button.dart
> +enum ChoiceEventsEnum {
已完成

2023-05-26 09:31 UTC, jackychiu0207 reviewed
review done

2023-05-26 10:10 UTC, SiongSng approved these changes
LGTM

2023-05-28 07:08 UTC, merged